services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    env_file:
      - .env  # <--- Esto le dice a Docker: "Lee las variables de AWS de aquí"
    restart: always