spring.application.name=modulos
jwt.secret=REPLACE_WITH_LOCAL_JWT_SECRET
jwt.expiration-ms=86400000
spring.datasource.url=jdbc:postgresql://localhost:5432/ERP_OPENSOURCE_DB
spring.datasource.username=postgres
spring.datasource.password=REPLACE_WITH_DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
