spring.application.name=modulos
spring.config.import=optional:file:.env[.properties]
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- LIMPIEZA DE RUIDO SQL ---
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# --- LOGS DE PETICIONES WEB ENFOCADOS ---
# DispatcherServlet nos dirá cuándo termina una petición y con qué código
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
# Seguridad simplificada
logging.level.org.springframework.security=INFO
spring.web.error.include-message=always
spring.web.error.include-stacktrace=never
spring.web.error.include-binding-errors=never

# --- CREDENCIALES MAESTRAS DE ODOO ---
odoo.master.url=${ODOO_MASTER_URL:}
odoo.master.db=${ODOO_MASTER_DB:}
odoo.master.user=${ODOO_MASTER_USER:}
odoo.master.password=${ODOO_MASTER_PASSWORD:}

